# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Exekuce - Lepší systém
email: lukas.kolarik@pirati.cz
description: 
keywords: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://exekuce.pirati.cz" # the base hostname & protocol for your site

administrator:
  email: jan.suchanek@gmail.com # mail kam pujdou chybove vystupy

theme: jekyll-theme-pirati

sass:
  style: compressed
  sass_dir: _sass

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-environment-variables

paginate_path: "/aktuality/:num/"
paginate: 11

pagination:
  per_page: 2
  limit: false

exclude:
  - Dockerfile
  - docker-compose.yml
  - deploy_rsa_sandbox.enc
  - deploy_rsa_sandbox.pub
  - navod.md
  - readme.md
  - Gemfile
  - Gemfile.lock
  - vendor

permalink: /tiskove-zpravy/:title/
collections:
  people:
    output: true
    root: /clenove/
    permalink: /clenove/:path/

  program:
    output: true
    permalink: /komunalni-volby-2018/program/:path/

  # Sole purpose is to create candidate lists in separate files.
  candidatelists:
    output: false

defaults:   # defaults values for collection scope
  -
    scope:
      path: "_people"
    values:
      layout: "person"
      rbar:
        - foto
        - personContact
        - people
      keywords: členové, příznivci, lidé
  -
    scope:
      path: "_program"
    values:
      layout: "program-post"
      rbar:
        - garant
        - program
      keywords: program, volby, 2018, komunální volby

organization:
  name: Lepší systém exekucí
  shortName: Lepší systém exekucí
  email: KolarikL@psp.cz
  contactUid: lukas.kolarik
  phone: +420 608 770 778
  address: |
    Na Moráni 3
    120 00 Praha 2
  #residenceImg: miscellaneous.jpg
  mapLink: https://mapy.cz/s/2N7Yv
  redmineLink: https://redmine.pirati.cz/projects
  dataBoxId: b2i4r6j
  transparentAccount: 2100048174/2010
  transparentAccountSpecificSymbol: 110111

contactSummaryItems:
  - type: organizationEmail
  - type: organizationRedmineLink
  - type: organizationPhone
  - type: organizationTransparentAccount
    includeMoreLink: true
  - type: custom
    iconClass: fa fa-facebook
    label: Facebooková stránka
    body: <a href="https://www.facebook.com/pirat.kolarik/" target="_blank">Lukáš Kolařík</a>

calendar:
  # To enable a nicer calendar, make sure you start jekyll with GOOGLE_CALENDAR_APIKEY=[apikey] bundle exec jekyll serve
  title: Nadcházející události
  id: 0lmvrce8ph0t1mqa5uk4v98ui4@group.calendar.google.com
  page: https://calendar.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showDate=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=500&amp;wkst=2&amp;hl=cs&amp;bgcolor=%23FFFFFF&amp;src=0lmvrce8ph0t1mqa5uk4v98ui4%40group.calendar.google.com&amp;color=%23B1365F&amp;src=lpvmfpogihrca3lqs9p2udae0k%40group.calendar.google.com&amp;color=%238D6F47&amp;ctz=Europe%2FPrague

facebook:
  profilePage: https://www.facebook.com/pirat.kolarik/
  loadSDK: true
  appId: 1526197851008996

twitter:
  profile: kolarik_lukas
  loadSDK: true


gplus:
  profilePage: https://plus.google.com/u/0/+piratskastrana

#forum:
#  page: https://forum.pirati.cz/

github:
  url: https://github.com/pirati-web/exekuce.pirati.cz/
  branch: master

emptyArray: []

assets:
  source_maps: true
  compression: true
  gzip: false
  plugins:
    css: { autoprefixer: {}}
    img:
      optim:
        jpegoptim:
          strip: all
          max_quality: 80
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
  sources:
    - vendor/bundle/ruby/2.5.0/gems/jekyll-theme-pirati-7.4.0/_sass
    - assets/css
    - assets/fonts
    - assets/video
    - assets/img
    - _sass
    

